# Your Name or Company
title: We eloped!

# Description of your website. This is used for social sharing.
description:  Clemente and Virginia were married on October 22nd, 2021 at Poet's Seat Tower in Greenfield, MA.

markdown: kramdown

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
